Repository Vibe-House-LLC/memeSRC, pull requests merged in 2024-04, with the labels that each got.

#259 Add starter faqs page
  src/pages/FAQPage.js
  src/routes.js
Labels: documentation, enhancement

#263 Improve search result relevance
  amplify/backend/function/memesrcSearchV2/src/index.js
  package-lock.json
  package.json
  src/pages/V2SearchPage.js
Labels: enhancement

#264 Fix donation redirect
  package-lock.json
  package.json
  src/routes.js
Labels: enhancement

#265 Temporarily disable animated results and hide search banner
  package-lock.json
  package.json
  src/pages/V2SearchPage.js
Labels: enhancement

#266 Update total count on homepage
  package-lock.json
  package.json
  src/pages/EditorNewProjectPage.js
  src/sections/search/FullScreenSearch.js
Labels: enhancement

#269 Add clear caption button and fix empty subtitles
  src/pages/V2FramePage.js
  src/utils/frameHandlerV2.js
Labels: enhancement

#270 Increase items per page to match v1
  package-lock.json
  package.json
  src/pages/V2EpisodePage.js
Labels: enhancement

#272 Display search result count and adjust ads
  package-lock.json
  package.json
  src/pages/V2EpisodePage.js
  src/pages/V2FramePage.js
  src/pages/V2SearchPage.js
Labels: enhancement

#273 Fix frame extractor scaling
  amplify/backend/function/frameExtractor/src/index.js
  amplify/team-provider-info.json
  package-lock.json
  package.json
Labels: bug, enhancement

#274 Fix frame extraction
  amplify/backend/function/frameExtractor/src/index.js
  amplify/team-provider-info.json
Labels: bug, enhancement

#276 Adjust disclaimer agreement
  src/contexts/SubscribeDialog.js
Labels: enhancement

#277 Remove reliance on CloudFront for source data transfers
  amplify/backend/backend-config.json
  amplify/backend/function/frameExtractor/frameExtractor-cloudformation-template.json
  amplify/backend/function/frameExtractor/function-parameters.json
  amplify/backend/function/frameExtractor/src/index.js
  amplify/backend/function/memesrcSearchV2/function-parameters.json
  amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json
  amplify/backend/function/memesrcSearchV2/src/index.js
  amplify/backend/pnpm-lock.yaml
  amplify/team-provider-info.json
Labels: enhancement

#279 Add favorites feature
  package-lock.json
  package.json
  src/pages/FavoritesPage.js
  src/routes.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
  src/utils/fetchShows.js
Labels: enhancement

#280 Adjust configs to reduce cost
  amplify/backend/function/frameExtractor/frameExtractor-cloudformation-template.json
  amplify/backend/function/frameExtractor/src/index.js
  amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json
  amplify/team-provider-info.json
  package-lock.json
  package.json
  src/pages/V2EpisodePage.js
Labels: enhancement

#281 Optimize data transfer
  amplify/backend/function/memesrcSearchV2/src/index.js
  amplify/team-provider-info.json
Labels: enhancement

#283 Optimize logs to reduce CloudWatch costs
  amplify/backend/function/frameExtractor/src/index.js
  amplify/backend/function/memesrcSearchV2/src/index.js
  amplify/backend/function/memesrcUserFunction/src/index.js
  amplify/team-provider-info.json
Labels: enhancement

#288 Add search result skeletons
  package-lock.json
  package.json
  src/components/ImageSkeleton.js
  src/pages/V2SearchPage.js
Labels: enhancement

#289 Fix skeletons after loading
  src/pages/V2SearchPage.js
Labels: bug, enhancement

#290 Fix voting page errors
  package-lock.json
  package.json
  src/pages/VotingPage.js
Labels: bug, enhancement

#292 Add confirmation email design html
  emails/confirmation-email-design.html
Labels: enhancement

#294 Add account page poc
  src/pages/AccountPage.js
  src/routes.js
Labels: enhancement

#295 Add error handling to json parsing
  amplify/backend/function/memesrcSearchV2/src/index.js
Labels: bug, enhancement

#296 Add all favorites search
  package-lock.json
  package.json
  src/components/magic-popup/MagicPopup.js
  src/layouts/dashboard/header/AccountPopover.js
  src/pages/DashboardAliasPageRevised.js
  src/pages/DynamicRouteHandler.js
  src/pages/HomePage.js
  src/pages/V2EpisodePage.js
  src/pages/V2SearchPage.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
  src/utils/frameHandlerV2.js
  src/utils/loadRandomFrame.js
  src/utils/loadV2Csv.js
Labels: enhancement

#298 Use local storage for index selection cache
  src/pages/FavoritesPage.js
  src/utils/fetchShows.js
Labels: enhancement

#299 Add pro banner ad
  src/layouts/dashboard/DashboardLayout.js
  src/layouts/dashboard/header/index.js
Labels: enhancement

#300 Add demo for Facebook auth
  src/pages/FacebookAuthDemo.js
  src/routes.js
Labels: enhancement

#301 Fix bug with nearby subtitles
  src/utils/frameHandlerV2.js
Labels: bug, enhancement

#304 Fix s3 trigger prefix
  amplify/backend/function/S3Trigger016e2873/src/index.js
Labels: enhancement

#303 Add font formatting settings
  src/fonts/akbar.ttf
  src/global.css
  src/index.js
  src/pages/V2FramePage.js
Labels: enhancement
