Repository Vibe-House-LLC/memeSRC, pull requests merged in 2024-05, with the labels that each got.

#305 Add metadata refresh
  amplify/backend/api/memesrc/schema.graphql
  amplify/backend/pnpm-lock.yaml
  amplify/team-provider-info.json
  src/graphql/mutations.js
  src/graphql/queries.js
  src/graphql/schema.json
  src/graphql/subscriptions.js
  src/pages/DashboardAliasPageRevised.js
  src/sections/search/FullScreenSearch.js
Labels: enhancement

#306 Update create index to support font family input
  src/sections/server/CreateIndex.js
Labels: enhancement

#302 Trigger fallback for searches of 3+ indexes when OpenSearch is down
  amplify/backend/api/memesrc/schema.graphql
  amplify/backend/function/S3Trigger016e2873/src/index.js
  amplify/backend/function/memesrcSearchV2/src/index.js
  amplify/backend/pnpm-lock.yaml
  amplify/team-provider-info.json
  src/fonts/akbar.ttf
  src/global.css
  src/graphql/mutations.js
  src/graphql/queries.js
  src/graphql/schema.json
  src/graphql/subscriptions.js
  src/index.js
  src/pages/DashboardAliasPageRevised.js
  src/pages/V2FramePage.js
  src/sections/search/FullScreenSearch.js
  src/sections/server/CreateIndex.js
Labels: bug, enhancement

#307 Fix voting page
  package-lock.json
  package.json
  src/fonts/fr-bold.ttf
  src/global.css
  src/logo/logo.js
  src/pages/DashboardAliasPageRevised.js
  src/pages/V2EditorPage.js
  src/pages/V2FramePage.js
  src/routes.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
Labels: enhancement

#309 Fix font vector
  src/fonts/fr-bold.ttf
Labels: bug, enhancement

#310 Disable broken font
  src/fonts/fr-bold.ttf
  src/pages/V2FramePage.js
Labels: bug, enhancement

#314 Fix html sanitization
  package-lock.json
  package.json
  src/pages/V2EpisodePage.js
  src/pages/V2SearchPage.js
  src/utils/frameHandlerV2.js
Labels: bug, enhancement

#315 Fix subtitle decoding while browsing
  package-lock.json
  package.json
  src/pages/V2EpisodePage.js
  src/pages/V2SearchPage.js
  src/utils/frameHandlerV2.js
Labels: bug, enhancement

#316 Enable akbar font and use fontFamily from metadata as default
  package-lock.json
  package.json
  src/pages/V2FramePage.js
Labels: enhancement

#317 Fix frame extraction prefix and opensearch fallback
  amplify/backend/function/frameExtractor/src/index.js
  package-lock.json
  package.json
  src/pages/V2SearchPage.js
Labels: bug, enhancement

#318 Adjust ad placement
  src/pages/V2EditorPage.js
  src/pages/V2FramePage.js
Labels: enhancement

#319 Optimizing function storage to fix frame extractor
  amplify/backend/function/frameExtractor/src/index.js
Labels: bug, enhancement

#321 Add font settings to advanced editor layers
  package-lock.json
  package.json
  src/components/TextEditorControls.js
  src/pages/V2EditorPage.js
Labels: enhancement

#322 Fix bugs when editing custom images
  src/pages/V2EditorPage.js
  src/routes.js
Labels: bug, enhancement

#323 Fix metadata parsing
  src/utils/frameHandlerV2.js
Labels: enhancement

#326 Fix shows caching
  src/contexts/useShows.js
  src/pages/HomePage.js
  src/routes.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
Labels: enhancement

#328 Add shows handling to guest auth wrapper
  package-lock.json
  package.json
  src/UserContext.js
  src/layouts/dashboard/header/AccountPopover.js
  src/pages/HomePage.js
  src/routes.js
  src/sections/auth/login/GuestAuth.js
  src/sections/auth/login/LoginForm.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
  src/utils/fetchShowsRevised.js
Labels: bug, enhancement

#329 Guest auth bug fix
  src/sections/auth/login/GuestAuth.js
Labels: bug

#330 Save and reuse extracted image data
  amplify/backend/function/frameExtractor/frameExtractor-cloudformation-template.json
  amplify/backend/function/frameExtractor/function-parameters.json
  amplify/backend/function/frameExtractor/src/index.js
  amplify/backend/pnpm-lock.yaml
  amplify/team-provider-info.json
Labels: enhancement

#331 Clean up console logs
  src/components/magic-popup/MagicPopup.js
  src/contexts/SubscribeDialog.js
  src/contexts/useShows.js
  src/pages/HomePage.js
  src/pages/SiteWideMaintenance.js
  src/pages/V2FramePage.js
  src/pages/V2SearchPage.js
  src/sections/auth/login/GuestAuth.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
  src/utils/frameHandlerV2.js
  src/utils/getV2Metadata.js
Labels: enhancement

#332 Improve cache hit rate by rounding frame selections
  package-lock.json
  package.json
  src/pages/V2EditorPage.js
  src/pages/V2FramePage.js
  src/pages/V2SearchPage.js
Labels: enhancement

#333 Improve search relevance
  amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json
  amplify/backend/function/memesrcSearchV2/src/index.js
  package-lock.json
  package.json
Labels: enhancement

#334 Add front end geo restrictions
  amplify/backend/api/memesrc/schema.graphql
  amplify/backend/pnpm-lock.yaml
  amplify/team-provider-info.json
  src/contexts/SubscribeDialog.js
  src/graphql/mutations.js
  src/graphql/queries.js
  src/graphql/schema.json
  src/graphql/subscriptions.js
  src/utils/geo/mappings.js
  src/utils/geo/useUserLocation.js
Labels: enhancement

#335 Update Terms of Service
  package-lock.json
  package.json
  src/sections/legal/TermsOfService.js
Labels: documentation, enhancement

#336 Save format settings per user-index in localstorage
  package-lock.json
  package.json
  src/pages/V2FramePage.js
Labels: enhancement

#337 Fix bugs with searching and navigating
  package-lock.json
  package.json
  src/pages/V2EditorPage.js
  src/pages/V2FramePage.js
  src/sections/search/ipfs-search-bar.js
Labels: bug

#339 Add collage tool (early access)
  amplify/backend/api/APIGatewayAuthStack.json
  amplify/backend/pnpm-lock.yaml
  amplify/backend/yarn.lock
  package-lock.json
  package.json
  src/layouts/dashboard/nav/config.js
  src/pages/CollagePage.js
  src/routes.js
Labels: enhancement

#340 Improve discoverability of collage tool
  package-lock.json
  package.json
  src/components/nav-section/NavSection.js
  src/layouts/dashboard/nav/config.js
  src/pages/EditorNewProjectPage.js
  src/sections/search/FullScreenSearch.js
Labels: enhancement

#342 Unblock canada
  package-lock.json
  package.json
  src/contexts/SubscribeDialog.js
  src/sections/legal/TermsOfService.js
Labels: enhancement

#344 Improve dynamic route handling
  src/pages/DynamicRouteHandler.js
Labels: enhancement

#345 Improve transition into reset favorites
  src/pages/DynamicRouteHandler.js
  src/sections/auth/login/GuestAuth.js
  src/sections/auth/login/LoginForm.js
  src/sections/search/FavoritesResetDialog.js
  src/sections/search/FullScreenSearch.js
Labels: bug, enhancement
