Repository Vibe-House-LLC/memeSRC, pull requests merged in 2025-09, with the labels that each got.

#567 Add optional chaining to filtered users
  package-lock.json
  package.json
  src/sections/@dashboard/user/user-list.js
Labels: bug

#571 Add handler for indexing function
  amplify/backend/api/publicapi/cli-inputs.json
  amplify/backend/backend-config.json
  amplify/backend/function/memesrcIndexAndPublish/src/index.js
  amplify/backend/function/memesrcStartIndexingAndPublishing/amplify.state
  amplify/backend/function/memesrcStartIndexingAndPublishing/custom-policies.json
  amplify/backend/function/memesrcStartIndexingAndPublishing/function-parameters.json
  amplify/backend/function/memesrcStartIndexingAndPublishing/memesrcStartIndexingAndPublishing-cloudformation-template.json
  amplify/backend/function/memesrcStartIndexingAndPublishing/parameters.json
  amplify/backend/function/memesrcStartIndexingAndPublishing/src/event.json
  amplify/backend/function/memesrcStartIndexingAndPublishing/src/index.js
  amplify/backend/function/memesrcStartIndexingAndPublishing/src/package-lock.json
  amplify/backend/function/memesrcStartIndexingAndPublishing/src/package.json
  amplify/backend/function/memesrcUpdateMedia/function-parameters.json
  amplify/backend/function/memesrcUpdateMedia/memesrcUpdateMedia-cloudformation-template.json
  amplify/backend/function/memesrcUpdateMedia/src/index.js
  amplify/team-provider-info.json
  src/pages/AdminFileReview.tsx
  src/sections/@dashboard/admin/uploads/components/source-media-details-dialog.tsx
  src/sections/@dashboard/admin/uploads/components/source-media-row.tsx
  src/sections/@dashboard/admin/uploads/review-upload.tsx
Labels: enhancement

#574 Remove secret for upcoming feature
  amplify/backend/function/memesrcOpenAI/function-parameters.json
  amplify/backend/function/memesrcOpenAI/memesrcOpenAI-cloudformation-template.json
  amplify/backend/function/memesrcOpenAI/src/index.js
Labels: bug, enhancement

#573 Add event logging
  README_EVENTS.md
  amplify/backend/api/memesrc/schema.graphql
  amplify/backend/function/memesrcAxiosLayer/memesrcAxiosLayer-awscloudformation-template.json
  amplify/backend/function/memesrcDynamoDBLayer/memesrcDynamoDBLayer-awscloudformation-template.json
  amplify/backend/function/memesrcGraphQlLayer/memesrcGraphQlLayer-awscloudformation-template.json
  amplify/backend/function/memesrcOpenSearchLayer/memesrcOpenSearchLayer-awscloudformation-template.json
  amplify/backend/function/memesrcS3Layer/memesrcS3Layer-awscloudformation-template.json
  amplify/backend/function/memesrcSesLayer/memesrcSesLayer-awscloudformation-template.json
  src/components/FavoriteToggle.js
  src/components/collage/components/BulkUploadSection.js
  src/components/floating-action-buttons/FloatingActionButtons.js
  src/components/library/LibraryBrowser.jsx
  src/graphql/mutations.js
  src/graphql/queries.js
  src/graphql/schema.json
  src/graphql/subscriptions.js
  src/layouts/dashboard/nav/config.js
  src/pages/AdminUsageEventsLog.tsx
  src/pages/CollagePage.js
  src/pages/HomePage.js
  src/pages/V2EditorPage.js
  src/pages/V2EpisodePage.js
  src/pages/V2FramePage.js
  src/pages/V2SearchPage.js
  src/routes.js
  src/sections/search/ipfs-search-bar.js
  src/utils/trackUsageEvent.ts
Labels: enhancement

#577 Improve index selection
  src/components/FavoriteToggle.js
  src/components/SeriesSelectorDialog.tsx
  src/layouts/dashboard/header/AccountPopover.js
  src/layouts/dashboard/header/index.js
  src/pages/AccountPage.js
  src/pages/DynamicRouteHandler.js
  src/pages/FavoritesPage.js
  src/sections/auth/login/CheckAuth.js
  src/sections/auth/login/GuestAuth.js
  src/sections/auth/login/LoginForm.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
  src/utils/githubReleases.ts
  src/utils/storage.ts
Labels: enhancement

#585 Improve various designs
  src/components/search/UnifiedSearchBar.tsx
  src/pages/HomePage.js
  src/pages/V2EditorPage.js
  src/pages/V2FramePage.js
  src/pages/V2SearchPage.js
  src/routes.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/ipfs-search-bar.js
Labels: enhancement

#586 Add cloudfront invalidation to index and publish function
  amplify/backend/function/memesrcAxiosLayer/memesrcAxiosLayer-awscloudformation-template.json
  amplify/backend/function/memesrcDynamoDBLayer/memesrcDynamoDBLayer-awscloudformation-template.json
  amplify/backend/function/memesrcGraphQlLayer/memesrcGraphQlLayer-awscloudformation-template.json
  amplify/backend/function/memesrcIndexAndPublish/custom-policies.json
  amplify/backend/function/memesrcIndexAndPublish/memesrcIndexAndPublish-cloudformation-template.json
  amplify/backend/function/memesrcIndexAndPublish/src/index.js
  amplify/backend/function/memesrcOpenSearchLayer/memesrcOpenSearchLayer-awscloudformation-template.json
  amplify/backend/function/memesrcS3Layer/memesrcS3Layer-awscloudformation-template.json
  amplify/backend/function/memesrcSesLayer/memesrcSesLayer-awscloudformation-template.json
  amplify/team-provider-info.json
Labels: enhancement

#587 Update indexing function to remove index if it exists before reindexing
  amplify/backend/function/memesrcIndexAndPublish/src/index.js
Labels: bug, enhancement

#589 Improve selector behavior
  package-lock.json
  package.json
  src/components/SeriesSelectorDialog.tsx
  src/components/search/UnifiedSearchBar.tsx
Labels: enhancement
