Repository Vibe-House-LLC/memeSRC, pull requests merged in 2025-08, with the labels that each got.

#518 fix: improve favorites sorting and persistence
  src/components/collage/components/MyLibrary.js
Labels: codex

#517 Add favorites to library and improve ui
  src/components/collage/components/MyLibrary.js
Labels: enhancement

#519 Add reset and settings buttons to collage preview
  src/components/collage/components/CollageLayoutComponents.js
  src/components/collage/steps/CollageImagesStep.js
  src/pages/CollagePage.js
Labels: enhancement

#520 Fix race condition when saving images to library
  src/components/collage/hooks/useCollageState.js
Labels: codex

#522 Bug fixes for library
  src/components/collage/components/BulkUploadSection.js
  src/components/collage/components/CollagePreview.js
  src/pages/V2FramePage.js
Labels: bug, enhancement

#523 Replace buttons on library multi-select
  src/components/collage/components/MyLibrary.js
Labels: enhancement

#526 Update amplify functions
  amplify/backend/function/AdminQueries9e1cafc6/AdminQueries9e1cafc6-cloudformation-template.json
  amplify/backend/function/AdminQueries9e1cafc6/src/package-lock.json
  amplify/backend/function/S3Trigger016e2873/S3Trigger016e2873-cloudformation-template.json
  amplify/backend/function/S3Trigger016e2873/src/package-lock.json
  amplify/backend/function/frameExtractor/src/package.json
  amplify/backend/function/memesrcAggregateVotes/memesrcAggregateVotes-cloudformation-template.json
  amplify/backend/function/memesrcAggregateVotes/src/package-lock.json
  amplify/backend/function/memesrcAggregateVotes/src/yarn.lock
  amplify/backend/function/memesrcAnalyticsAddDailyPartition/memesrcAnalyticsAddDailyPartition-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsAddDailyPartition/src/package-lock.json
  amplify/backend/function/memesrcAnalyticsInitDBs/memesrcAnalyticsInitDBs-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsInitDBs/src/package-lock.json
  amplify/backend/function/memesrcAnalyticsMsck/memesrcAnalyticsMsck-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsMsck/src/package-lock.json
  amplify/backend/function/memesrcAnalyticsReporting/memesrcAnalyticsReporting-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsReporting/src/package-lock.json
  amplify/backend/function/memesrcGif/memesrcGif-cloudformation-template.json
  amplify/backend/function/memesrcGif/src/package-lock.json
  amplify/backend/function/memesrcGif/src/yarn.lock
  amplify/backend/function/memesrcGraphQL/memesrcGraphQL-cloudformation-template.json
  amplify/backend/function/memesrcGraphQL/src/package-lock.json
  amplify/backend/function/memesrcIndexToOpenSearch/memesrcIndexToOpenSearch-cloudformation-template.json
  amplify/backend/function/memesrcIndexToOpenSearch/src/package-lock.json
  amplify/backend/function/memesrcPublicStripeFunction/memesrcPublicStripeFunction-cloudformation-template.json
  amplify/backend/function/memesrcPublicStripeFunction/src/package-lock.json
  amplify/backend/function/memesrcRecoverUsername/memesrcRecoverUsername-cloudformation-template.json
  amplify/backend/function/memesrcRecoverUsername/src/package-lock.json
  amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json
  amplify/backend/function/memesrcSearchV2/src/package-lock.json
  amplify/backend/function/memesrcStripeCallback/memesrcStripeCallback-cloudformation-template.json
  amplify/backend/function/memesrcStripeCallback/src/package-lock.json
  amplify/backend/function/memesrcThumbnailZipExtractor/memesrcThumbnailZipExtractor-cloudformation-template.json
  amplify/backend/function/memesrcThumbnailZipExtractor/src/package-lock.json
  amplify/backend/function/memesrcUUID/memesrcUUID-cloudformation-template.json
  amplify/backend/function/memesrcUUID/src/package-lock.json
  amplify/backend/function/memesrcUserFunction/memesrcUserFunction-cloudformation-template.json
  amplify/backend/function/memesrcUserFunction/src/package-lock.json
  amplify/backend/function/memesrcVote/memesrcVote-cloudformation-template.json
  amplify/backend/function/memesrcVote/src/package-lock.json
  amplify/backend/function/memesrcVoteSearchSeries/memesrcVoteSearchSeries-cloudformation-template.json
  amplify/backend/function/memesrcVoteSearchSeries/src/yarn.lock
  amplify/backend/function/memesrcc3c71449PreSignup/memesrcc3c71449PreSignup-cloudformation-template.json
  amplify/backend/function/memesrcc3c71449PreSignup/src/package-lock.json
  amplify/team-provider-info.json
Labels: enhancement

#527 Clean up library implementation
  amplify/backend/function/AdminQueries9e1cafc6/AdminQueries9e1cafc6-cloudformation-template.json
  amplify/backend/function/AdminQueries9e1cafc6/src/package-lock.json
  amplify/backend/function/S3Trigger016e2873/S3Trigger016e2873-cloudformation-template.json
  amplify/backend/function/S3Trigger016e2873/src/package-lock.json
  amplify/backend/function/frameExtractor/src/package.json
  amplify/backend/function/memesrcAggregateVotes/memesrcAggregateVotes-cloudformation-template.json
  amplify/backend/function/memesrcAggregateVotes/src/package-lock.json
  amplify/backend/function/memesrcAggregateVotes/src/yarn.lock
  amplify/backend/function/memesrcAnalyticsAddDailyPartition/memesrcAnalyticsAddDailyPartition-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsAddDailyPartition/src/package-lock.json
  amplify/backend/function/memesrcAnalyticsInitDBs/memesrcAnalyticsInitDBs-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsInitDBs/src/package-lock.json
  amplify/backend/function/memesrcAnalyticsMsck/memesrcAnalyticsMsck-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsMsck/src/package-lock.json
  amplify/backend/function/memesrcAnalyticsReporting/memesrcAnalyticsReporting-cloudformation-template.json
  amplify/backend/function/memesrcAnalyticsReporting/src/package-lock.json
  amplify/backend/function/memesrcGif/memesrcGif-cloudformation-template.json
  amplify/backend/function/memesrcGif/src/package-lock.json
  amplify/backend/function/memesrcGif/src/yarn.lock
  amplify/backend/function/memesrcGraphQL/memesrcGraphQL-cloudformation-template.json
  amplify/backend/function/memesrcGraphQL/src/package-lock.json
  amplify/backend/function/memesrcIndexToOpenSearch/memesrcIndexToOpenSearch-cloudformation-template.json
  amplify/backend/function/memesrcIndexToOpenSearch/src/package-lock.json
  amplify/backend/function/memesrcPublicStripeFunction/memesrcPublicStripeFunction-cloudformation-template.json
  amplify/backend/function/memesrcPublicStripeFunction/src/package-lock.json
  amplify/backend/function/memesrcRecoverUsername/memesrcRecoverUsername-cloudformation-template.json
  amplify/backend/function/memesrcRecoverUsername/src/package-lock.json
  amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json
  amplify/backend/function/memesrcSearchV2/src/package-lock.json
  amplify/backend/function/memesrcStripeCallback/memesrcStripeCallback-cloudformation-template.json
  amplify/backend/function/memesrcStripeCallback/src/package-lock.json
  amplify/backend/function/memesrcThumbnailZipExtractor/memesrcThumbnailZipExtractor-cloudformation-template.json
  amplify/backend/function/memesrcThumbnailZipExtractor/src/package-lock.json
  amplify/backend/function/memesrcUUID/memesrcUUID-cloudformation-template.json
  amplify/backend/function/memesrcUUID/src/package-lock.json
  amplify/backend/function/memesrcUserFunction/memesrcUserFunction-cloudformation-template.json
  amplify/backend/function/memesrcUserFunction/src/package-lock.json
  amplify/backend/function/memesrcVote/memesrcVote-cloudformation-template.json
  amplify/backend/function/memesrcVote/src/package-lock.json
  amplify/backend/function/memesrcVoteSearchSeries/memesrcVoteSearchSeries-cloudformation-template.json
  amplify/backend/function/memesrcVoteSearchSeries/src/yarn.lock
  amplify/backend/function/memesrcc3c71449PreSignup/memesrcc3c71449PreSignup-cloudformation-template.json
  amplify/backend/function/memesrcc3c71449PreSignup/src/package-lock.json
  amplify/team-provider-info.json
  src/components/collage/components/CollagePreview.js
  src/components/floating-action-buttons/FloatingActionButtons.js
  src/pages/V2FramePage.js
Labels: enhancement

#516 Add photo library features
  src/components/animated/CollageAnimatedIcon.js
  src/components/collage/components/BulkUploadSection.js
  src/components/collage/components/CanvasCollagePreview.js
  src/components/collage/components/CollageLayoutComponents.js
  src/components/collage/components/CollagePreview.js
  src/components/collage/components/CollageResultDialog.js
  src/components/collage/hooks/useCollageState.js
  src/components/collage/steps/CollageImagesStep.js
  src/components/collage/steps/CollageSettingsStep.js
  src/components/floating-action-buttons/FloatingActionButtons.js
  src/components/library/ActionBar.jsx
  src/components/library/LibraryBrowser.jsx
  src/components/library/LibraryGrid.jsx
  src/components/library/LibraryTile.jsx
  src/components/library/PreviewDialog.jsx
  src/components/library/UploadTile.jsx
  src/components/library/index.js
  src/components/nav-section/CollageNavTeaser.js
  src/hooks/library/useLibraryData.js
  src/hooks/library/useSelection.js
  src/layouts/dashboard/nav/config.js
  src/pages/CollageAnimatedIconDemoPage.js
  src/pages/CollagePage.js
  src/pages/LibraryPage.js
  src/pages/V2FramePage.js
  src/routes.js
  src/utils/library/resizeImage.js
  src/utils/library/saveImageToLibrary.js
  src/utils/library/storage.js
  v3/app/collage/utils/gridUtils.ts
Labels: enhancement

#528 Update v3 dependencies
  v3/package-lock.json
Labels: dependencies

#529 Update backend function pnpm lock
  amplify/backend/pnpm-lock.yaml
  amplify/backend/yarn.lock
Labels: dependencies

#534 Beging gradual typescript migration
  .eslintrc
  jsconfig.json
  package-lock.json
  package.json
  src/components/ImageSkeleton.tsx
  src/components/logo/Logo.tsx
  src/components/logo/index.js
  src/components/svg-color/SvgColor.tsx
  src/components/svg-color/index.js
  src/hooks/useSearchDetails.ts
  src/layouts/dashboard/header/index.js
  src/pages/V2SearchPage.js
  src/sections/legal/PrivacyPolicy.js
  src/sections/legal/TermsOfService.js
  tsconfig.json
Labels: enhancement

#537 Add releases page for version history
  src/layouts/dashboard/nav/config.js
  src/pages/ReleasesPage.tsx
  src/routes.js
  src/theme/globalStyles.js
Labels: enhancement

#540 Add auto release notification
  src/pages/ReleasesPage.tsx
  src/sections/search/FullScreenSearch.js
  src/utils/githubReleases.ts
Labels: enhancement

#556 Add aws-sdk packages to lambda functions that use it
  amplify/backend/function/memesrcAggregateVotes/src/package.json
  amplify/backend/function/memesrcIndexToOpenSearch/src/package.json
  amplify/backend/function/memesrcOpenSearch/src/package.json
  amplify/backend/function/memesrcPublicStripeFunction/src/package.json
Labels: bug

#555 Simplify collage page content
  src/components/collage/components/BulkUploadSection.js
  src/components/collage/components/EarlyAccessFeedback.js
  src/pages/CollagePage.js
Labels: enhancement

#562 Add new magic editor (admin preview)
  src/components/collage/components/CanvasCollagePreview.js
  src/components/collage/components/CaptionEditor.js
  src/components/collage/components/CollagePreview.js
  src/components/magic-editor/MagicEditor.tsx
  src/pages/CollagePage.js
  src/pages/MagicPage.tsx
  src/routes.js
  src/utils/mockMagicEdit.ts
Labels: enhancement

#563 Fix colors on update notice
  package-lock.json
  package.json
  src/sections/search/FullScreenSearch.js
Labels: bug, enhancement
