Repository Vibe-House-LLC/memeSRC, pull requests merged in 2025-07, with the labels that each got.

#425 Improve collage subtitle tool
  src/components/collage/components/CanvasCollagePreview.js
  src/components/collage/components/CollageLayoutComponents.js
  src/components/collage/components/CollagePreview.js
  src/components/collage/hooks/useCollageState.js
  src/components/collage/steps/CollageImagesStep.js
  src/components/floating-action-buttons/FloatingActionButtons.js
  src/pages/CollagePage.js
Labels: enhancement

#427 Improve collage page and fix bugs
  src/components/collage/components/CanvasCollagePreview.js
Labels: bug, enhancement

#426 Add dismiss behavior for subtitle settings
  src/components/collage/components/CanvasCollagePreview.js
Labels: enhancement

#429 Fix styling for non-active collage frames
  src/components/collage/components/CanvasCollagePreview.js
Labels: bug, enhancement

#432 Add rotation slider to collage preview
  src/components/collage/components/CanvasCollagePreview.js
Labels: enhancement

#433 Add dismiss behavior to reposition mode
  src/components/collage/components/CanvasCollagePreview.js
Labels: enhancement

#436 Fix text wrapping on export
  src/components/collage/components/CanvasCollagePreview.js
Labels: bug

#437 Add captions and additional tools to the collage editor
  package-lock.json
  package.json
  src/App.js
  src/components/TextEditorControls.js
  src/components/collage/components/CanvasCollagePreview.js
  src/components/collage/components/CollageLayoutComponents.js
  src/components/collage/components/CollagePreview.js
  src/components/collage/components/WelcomeMessage.js
  src/components/collage/hooks/useCollageState.js
  src/components/collage/steps/CollageImagesStep.js
  src/components/floating-action-buttons/FloatingActionButtons.js
  src/contexts/CollageContext.js
  src/pages/CollagePage.js
  src/pages/V2FramePage.js
  src/sections/search/FullScreenSearch.js
  src/sections/search/TopBannerSeachRevised.js
  src/sections/search/TopBannerSearch.js
  src/sections/search/ipfs-search-bar.js
  src/utils/fonts.js
Labels: enhancement

#442 Add v3 starter frame page and favorites
  v3/app/SearchPage.tsx
  v3/app/[indexId]/search/[searchTerms]/PaginatedResults.tsx
  v3/app/[indexId]/search/[searchTerms]/page.tsx
  v3/app/components/SearchForm.tsx
  v3/app/frame/[showId]/[season]/[episode]/[frameNumber]/FrameActions.tsx
  v3/app/frame/[showId]/[season]/[episode]/[frameNumber]/page.tsx
  v3/app/layout.tsx
  v3/components/FavoritesStar.tsx
  v3/components/ui/dropdown-searchable.tsx
  v3/contexts/FavoritesContext.tsx
Labels: enhancement

#443 Fix collage collector visibility
  package-lock.json
  package.json
  src/pages/V2FramePage.js
Labels: bug, enhancement

#448 Consolidate collage frame action buttons
  src/components/collage/components/CanvasCollagePreview.js
Labels: enhancement, codex

#449 Improve scrolling and sizing on homepage
  package-lock.json
  package.json
  src/sections/search/FullScreenSearch.js
  src/sections/search/HomePageSection.js
Labels: enhancement, codex

#451 Resolve linter warnings
  src/components/FavoriteToggle.js
  src/components/ImageSkeleton.js
  src/components/LoadingBackdrop.js
  src/components/TextEditorControls.js
  src/components/collage/components/BulkUploadSection.js
  src/components/collage/components/CollageLayoutComponents.js
  src/components/collage/components/CollageResultDialog.js
  src/components/collage/components/EarlyAccessFeedback.js
  src/components/logo/Logo.js
  src/pages/V2FramePage.js
  src/utils/zipToImage.js
Labels: enhancement, codex

#453 Fix caption swap when rearranging panels
  src/components/collage/components/CanvasCollagePreview.js
Labels: bug, enhancement, codex

#457 Resolve lint warnings
  src/App.js
  src/components/CountdownTimer.js
  src/components/ImageEditorControls.js
  src/components/TvdbSearch/TvdbSearch.js
  src/components/alias-table-row/AliasTableRow.js
  src/components/collage/components/CanvasCollagePreview.js
  src/components/collage/components/CollagePreview.js
  src/components/collage/components/CollageUIComponents.js
  src/components/collage/config/CollageConfig.js
  src/components/collage/config/layouts/LayoutUtils.js
  src/components/collage/hooks/useCollageState.js
  src/components/collage/steps/CollageImagesStep.js
  src/components/floating-action-buttons/FloatingActionButtons.js
  src/components/ipfs/add-cid-popup.js
  src/components/nav-section/CollageNavTeaser.js
  src/components/nav-section/NavSection.js
  src/contexts/CollageContext.js
  src/contexts/useSubscribeDialog.js
  src/index.js
  src/layouts/dashboard/nav/config.js
  src/logo/logo.js
  src/pages/AccountPage.js
  src/pages/CollagePageLegacy.js
  src/pages/ContributorRequest.js
  src/pages/DashboardAliasPageRevised.js
  src/pages/DashboardAppPage.js
  src/pages/DashboardCidPage.js
  src/pages/EditorPage.js
  src/pages/FacebookAuthDemo.js
  src/pages/PricingPage.js
  src/pages/ServerPage.js
  src/pages/SourceMediaFileList.js
  src/pages/SourceMediaList.js
  src/pages/UserPage.js
  src/pages/V2EditorPage.js
  src/pages/VotingPage.js
  src/sections/@dashboard/series/SeriesCard.js
  src/sections/@dashboard/series/UploadToSeriesPage.js
  src/sections/auth/login/GuestAuth.js
  src/sections/auth/login/LoginForm.js
  src/sections/search/ipfs-search-bar.js
  src/sections/server/CreateIndex.js
  src/utils/editorFunctions.js
  src/utils/frameHandler.js
  src/utils/frameHandlerV2.js
  src/utils/loadRandomFrame.js
  src/utils/loadV2Csv.js
  src/utils/videoFrameExtractor.js
Labels: enhancement, codex

#465 Fix ESLint warnings
  src/components/collage/config/CollageConfig.js
  src/contexts/V2SearchDetailsProvider.js
  src/pages/AuthPage.js
  src/pages/FAQPage.js
  src/pages/SubtitleViewerPage.js
  src/pages/V2EditorPage.js
  src/pages/V2SearchPage.js
  src/pages/VotingPage.js
Labels: codex

#467 Fix lint warnings
  src/components/collage/steps/CollageSettingsStep.js
  src/pages/BasePage.js
  src/pages/InpaintingPage.js
  src/pages/SourceMediaList.js
  src/pages/UserPage.js
  src/pages/V2EpisodePage.js
  src/sections/@dashboard/website-settings/MaintenanceModes.js
  src/utils/StripeWatcher.js
Labels: codex

#468 Fix ESLint warnings
  src/components/collage/components/CollagePreview.js
  src/components/collage/components/CollageUIComponents.js
  src/pages/DashboardCidPage.js
  src/pages/InvoicesListPage.js
  src/pages/WebsiteSettings.js
  src/sections/auth/login/ForgotUsernameForm.js
  src/sections/server/CreateIndex.js
Labels: codex

#470 Fix ESLint warnings
  src/components/nav-section/CollageNavTeaser.js
  src/contexts/SubscribeDialog.js
  src/layouts/dashboard/nav/index.js
  src/pages/DashboardAliasPageRevised.js
  src/pages/EditorPage.js
  src/pages/EditorProjectsPage.js
  src/pages/FacebookAuthDemo.js
  src/sections/auth/login/ForgotPasswordForm.js
  src/sections/server/ServerInfo.js
Labels: codex

#471 Resolve eslint warnings
  src/components/v2-feature-section/sections/platform-updates.js
  src/layouts/dashboard/DashboardLayout.js
  src/pages/AddToSeriesPage.js
  src/pages/CollagePageLegacy.js
  src/pages/DashboardAppPage.js
  src/pages/SiteWideMaintenance.js
  src/sections/@dashboard/series/UploadToSeriesPage.js
  src/sections/auth/login/VerifyForm.js
  src/sections/server/CidInput.js
Labels: codex

#472 Fix lint issues
  src/layouts/dashboard/header/NotificationsPopover.js
  src/layouts/dashboard/nav/config.js
  src/pages/AccountPage.js
  src/pages/CollagePage.js
  src/pages/DashboardSeriesPage.js
  src/pages/FavoritesPage.js
  src/pages/HomePage.js
  src/sections/search/ipfs-search-bar.js
Labels: codex

#476 Fix unused variable lint warnings
  src/components/collage/components/CanvasCollagePreview.js
  src/pages/ContributorRequest.js
  src/pages/EditorNewProjectPage.js
  src/sections/auth/login/SignupForm.js
  src/sections/search/FullScreenSearch.js
Labels: codex

#477 Fix remaining lint warnings
  src/components/collage/components/CanvasCollagePreview.js
  src/components/collage/components/DisclosureCard.js
  src/pages/EditorNewProjectPage.js
  src/pages/V2EditorPage.js
  src/utils/editorFunctions.js
Labels: codex

#492 Fix SEO issues with alt text and anchors
  .gitignore
  package-lock.json
  src/pages/EditorPage.js
  src/pages/Page404.js
  src/pages/V2EditorPage.js
  src/pages/V2FramePage.js
  src/sections/search/FullScreenSearch.js
Labels: codex

#505 Restore error logging
  src/pages/V2EditorPage.js
Labels: codex

#508 Improve library behavior and design
  src/components/collage/components/BulkUploadSection.js
  src/components/collage/components/CollageLayoutComponents.js
  src/components/collage/components/MyLibrary.js
  src/components/collage/hooks/useCollageState.js
  src/components/collage/steps/CollageSettingsStep.js
  src/pages/CollagePage.js
  src/pages/V2FramePage.js
Labels: enhancement

#511 Improve caching for collage library images
  src/components/collage/components/MyLibrary.js
Labels: enhancement, codex
